# pyperclip.pyi

def copy(text: str) -> None: ...
def paste() -> str: ...
def waitForPaste(timeout: float | None = ...) -> str: ...
def waitForNewPaste(paste_text: str, timeout: float | None = ...) -> str: ...

def is_available() -> bool: ...
def determine_clipboard() -> None: ...
def set_clipboard(cb: str) -> None: ...
def get_clipboard() -> str: ...

ClipboardException: type[Exception]
