import argparse
import msgspec
import requests
from _typeshed import Incomplete
from pathlib import Path
from rich.progress import Progress

EXTENSIONS: Incomplete
PLATFORMDIRS: Incomplete
CONFIG_FOLDER: Incomplete
DEFAULT_CONFIGURATION_PATH: Incomplete
DEFAULT_ENCODING: str

class DefaultConfig(msgspec.Struct):
    api_key: str = ...
    download_path: Path = ...
    resize_path: Path = ...
    txt_path: Path = ...

def parse_fappy() -> argparse.ArgumentParser: ...
def encode_hook(obj: Path | str) -> str: ...
def decode_hook(type_: type[Path], value: Path | str) -> Path | str: ...
def get_config_path(path: Path | None = None) -> Path: ...
def load_config(path: Path | None = None) -> DefaultConfig: ...
def save_config(configuration: DefaultConfig, path: Path | None = None) -> None: ...
def load_or_create_config(path: Path | None = None) -> DefaultConfig: ...

CONFIG: Incomplete

def ensure_directories_exist(config: DefaultConfig) -> None: ...
def create_retry() -> requests.Session: ...
def find_images(arg: Path) -> list[Path]: ...
def organize_pics(filenames: list[Path], resize: int | None = None) -> list[Path]: ...
def check_width(new_width: int, width: int) -> int: ...
def resize_pics(pic: Path, resize: int | None = None) -> Path: ...
def download_image(url: str) -> Path: ...
def upload_image(image_path: Path) -> tuple[str, str]: ...
def get_progress(process_type: str) -> tuple[Progress, Progress]: ...
def save_txt(path_name: Path, text_string: str) -> None: ...
def get_out() -> Path: ...
def format_links(link_format: str, link: str, image_id: str) -> str: ...
def change_url_suffix(url: str, new_suffix: str) -> str: ...
def is_url(s: str) -> bool: ...
def separate_sources(sources: list[str]) -> tuple[list[str], list[Path]]: ...
def main() -> None: ...
