from PIL.Image import Image

def quantize_raw_rgba_bytes(image_data: bytes, width: int, height: int, dithering_level: float = 1.0, max_colors: int = 256, min_quality: int = 0, max_quality: int = 100) -> bytes: ...
def quantize_pil_image(image: Image, dithering_level: float = 1.0, max_colors: int = 256, min_quality: int = 0, max_quality: int = 100) -> Image: ...